// Re-export all enum labels and color maps for convenient access
export {
  ProductStatusLabels,
  SalesOrderStatusLabels,
  SalesOrderStatusColors,
  PurchaseOrderStatusLabels,
  PurchaseOrderStatusColors,
  InspectionResultLabels,
  InspectionResultColors,
  ContainerPlanStatusLabels,
  ContainerPlanStatusColors,
  ContainerTypeLabels,
  LogisticsStatusLabels,
  LogisticsStatusColors,
  UserRoleLabels,
  CurrencyTypeLabels,
  PaymentMethodLabels,
  TradeTermLabels,
  UnitTypeLabels,
  LogisticsCostTypeLabels,
  AuditActionLabels,
} from '@/types/api';
